# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(help_text=b'Message status', max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_id', to='authentication.Users')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='chat.Message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='authentication.Users')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
    ]
